name: Tajimi Checker

on:
  schedule:
    - cron: '0 9 * * *'   # JST 18:00 → UTC 9:00
    - cron: '0 16 * * *'  # JST 1:00 → UTC 16:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Update data"
          git push
